# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 089d98d907da719540a969d3069768a067c0cc96e87914cb800fd7424b31479277377bdb5e42650e4e7d65ed274bc478cd99666f0c8400bc9e24115ecad2d74d
  aws_access_key_id: AKIAJNVNV6YV6ENZO75A
  aws_secret_access_key: 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
  s3_bucket_name: ara-promos

  FIREBASE_SERVER_API_KEY: AIzaSyArewave0lp1oXqc7HSJk6xMiBVR3fof24
test:
  secret_key_base: 3f7561ccbc35ec38fd718ad019a13594f6e2fb7787333fc60e4950f1847fce6e36a9989b6ec23bf63ebb8750f70b4fa07cd7df656af6dc68bff5dfe6e685b74f
  aws_access_key_id: AKIAJNVNV6YV6ENZO75A
  aws_secret_access_key: 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
  s3_bucket_name: ara-promos
  FIREBASE_SERVER_API_KEY: AIzaSyArewave0lp1oXqc7HSJk6xMiBVR3fof24
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  FIREBASE_SERVER_API_KEY: <%= ENV["FIREBASE_SERVER_API_KEY"] %>
